/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Libro;
import controlador.Registro;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author patri
 */
public class FrmLibro extends javax.swing.JFrame {
    Libro libro =   new Libro();  
    /**
     * Creates new form FrmLibro
     */
    public FrmLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDisponible = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdoSi = new javax.swing.JRadioButton();
        rdoNo = new javax.swing.JRadioButton();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        chkDisponible = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso de Libro");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Ingreso de Libros");

        jLabel2.setText("Titulo");

        jLabel3.setText("Autor");

        jLabel4.setText("Publicación");

        jLabel5.setText("Precio");

        jLabel6.setText("Disponible");

        jLabel7.setText("Listado de libros");

        grupoDisponible.add(rdoSi);
        rdoSi.setText("Si");

        grupoDisponible.add(rdoNo);
        rdoNo.setText("No");

        txtTitulo.setToolTipText("Ingrese el titulo del libro");

        txtAutor.setToolTipText("Ingrese un autor. Ej: Isaac Asimov");

        chkDisponible.setText("Si");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idLibro", "Titulo", "Autor", "Publicación", "Precio", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grilla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkDisponible)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTitulo)
                                        .addComponent(txtAutor)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14)
                                            .addComponent(txtAnio)))
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rdoSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoNo)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSi)
                    .addComponent(rdoNo))
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chkDisponible))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnListar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtTitulo.setText("");
        txtAutor.setText("");
        txtDia.setText("");
        txtMes.setText("");
        txtAnio.setText("");
        txtPrecio.setText("");
        chkDisponible.setSelected(false);
        txtTitulo.requestFocus();
        libro.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // validar // si estan en blanco
        if(txtTitulo.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el titulo del libro");
            txtTitulo.requestFocus();
            
        }
        else if(txtAutor.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el Autor del libro");
            txtTitulo.requestFocus();
            
        }
        else if(txtDia.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el día de la publicación");
            txtTitulo.requestFocus();
            
        }
        else if(txtMes.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el mes de la publicación");
            txtTitulo.requestFocus();
            
        }
        else if(txtAnio.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el año de la publicación");
            txtTitulo.requestFocus();
            
        }
        else if(txtPrecio.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el precio del libro");
            txtTitulo.requestFocus();
            
        }
        else
        {
            // flag /bandera = usuario quiere ingresar nuevo libro
            libro.setIdLibro(0);
            libro.setTitulo(txtTitulo.getText().toUpperCase());
            libro.setAutor(txtAutor.getText().toUpperCase());
            
            Date fecha;
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/mm/yyyy");
            try {
                // convierte el string en una fecha valida
                fecha = formatoFecha.parse(txtDia.getText() + "/" + txtMes.getText() + "/" + txtAnio.getText());
                libro.setPublicacion(fecha);
            } catch (ParseException ex) {
                Logger.getLogger(FrmLibro.class.getName()).log(Level.SEVERE, null, ex);
            }
            int precio = 0;
            // Integer.parseInt convierte el String en un numero (int)
            precio = Integer.parseInt(txtPrecio.getText());
            
            libro.setPrecio(precio);
            
            libro.setDisponible(chkDisponible.isSelected());
            //JOptionPane.showMessageDialog(this, libro);
            
            Registro r = new Registro();
            if(r.agregar(libro))
            {
                JOptionPane.showMessageDialog(this, "El libro fue guardado con éxito");
                btnLimpiar.doClick();
            }
            else
                JOptionPane.showMessageDialog(this, "Error al guardar el libro");
        }
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        Registro registro = new Registro();
        
        DefaultTableModel modelo = (DefaultTableModel) grilla.getModel();
        modelo.setRowCount(0);
        String titulo = txtTitulo.getText();
        List<Libro> lista = registro.buscarTitulo(titulo);
        
        //List<Libro> lista = registro.buscarTodos();
        for(Libro aux: lista)
        {
            modelo.addRow(new Object[]{   
                aux.getIdLibro(),
                aux.getTitulo(),
                aux.getAutor(),
                aux.getPublicacion(),
                aux.getPrecio(),
                aux.isDisponible()            
            });
        }
        
    }//GEN-LAST:event_btnListarActionPerformed

    private void grillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaMouseClicked
        // TODO add your handling code here:
        int row = grilla.getSelectedRow();        
        //int row = grilla.rowAtPoint(evt.getPoint());
        
        int id = 0;
        id = Integer.parseInt(grilla.getValueAt(row, 0).toString());
        libro.setIdLibro(id); // para que pueda modificar o eliminar
        txtTitulo.setText(grilla.getValueAt(row, 1).toString());
        txtAutor.setText(grilla.getValueAt(row, 2).toString());
        
        String fecha = "";
        fecha = grilla.getValueAt(row, 3).toString();
        System.out.println(fecha);
        txtDia.setText(fecha.substring(8)); // 2000/10/01
        txtMes.setText(fecha.substring(5, 7)); // 2000/10/01
        txtAnio.setText(fecha.substring(0,4)); // 2000/10/01
        
        txtPrecio.setText(grilla.getValueAt(row, 4).toString());
        
        chkDisponible.setSelected(grilla.getValueAt(row, 5).toString().equals("true"));

        
    }//GEN-LAST:event_grillaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        // validar // si estan en blanco
        if(libro.getIdLibro() < 1)// va a contener un valor cuando el usuario realiza un clic en la grilla
        {
            JOptionPane.showMessageDialog(this, "No se puede modificar, debe seleccionar una fila.");
            txtTitulo.requestFocus();
        }
        else if(txtTitulo.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el titulo del libro");
            txtTitulo.requestFocus();
            
        }
        else if(txtAutor.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el Autor del libro");
            txtTitulo.requestFocus();
            
        }
        else if(txtDia.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el día de la publicación");
            txtTitulo.requestFocus();
            
        }
        else if(txtMes.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el mes de la publicación");
            txtTitulo.requestFocus();
            
        }
        else if(txtAnio.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el año de la publicación");
            txtTitulo.requestFocus();
            
        }
        else if(txtPrecio.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Falta especificar el precio del libro");
            txtTitulo.requestFocus();
            
        }
        else
        {
            //libro.setIdLibro(0); No va esta linea pq no se podrá modificar. Está almacenando el id para modificar
            libro.setTitulo(txtTitulo.getText().toUpperCase());
            libro.setAutor(txtAutor.getText().toUpperCase());
            
            Date fecha;
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/mm/yyyy");
            try {
                // convierte el string en una fecha valida
                fecha = formatoFecha.parse(txtDia.getText() + "/" + txtMes.getText() + "/" + txtAnio.getText());
                libro.setPublicacion(fecha);
            } catch (ParseException ex) {
                Logger.getLogger(FrmLibro.class.getName()).log(Level.SEVERE, null, ex);
            }
            int precio = 0;
            // Integer.parseInt convierte el String en un numero (int)
            precio = Integer.parseInt(txtPrecio.getText());
            
            libro.setPrecio(precio);
            
            libro.setDisponible(chkDisponible.isSelected());
            //JOptionPane.showMessageDialog(this, libro);
            
            Registro r = new Registro();
            if(r.actualizar(libro))
            {
                JOptionPane.showMessageDialog(this, "El libro fue guardado con éxito");
                btnLimpiar.doClick();
            }
            else
                JOptionPane.showMessageDialog(this, "Error al guardar el libro");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(libro.getIdLibro() < 1)// va a contener un valor cuando el usuario realiza un clic en la grilla
        {
            JOptionPane.showMessageDialog(this, "No se puede modificar, debe seleccionar una fila.");
            txtTitulo.requestFocus();
        }
        else
        {
            Registro r = new Registro();
            if(r.eliminar(libro.getIdLibro()))
            {
                JOptionPane.showMessageDialog(this, "El libro fue eliminado con éxito");
                btnLimpiar.doClick();
            }
            else
                JOptionPane.showMessageDialog(this, "Error al eliminar el libro");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox chkDisponible;
    private javax.swing.JTable grilla;
    private javax.swing.ButtonGroup grupoDisponible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoNo;
    private javax.swing.JRadioButton rdoSi;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
